[workspace]
members = [
    "programs/*"
]

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1

[features]
idl-build = ["anchor-lang/idl-build"]

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
